config/routes.rb
# == Route Map
#
#                 Prefix Verb   URI Pattern                       Controller#Action
#     new_author_session GET    /authors/sign_in(.:format)        devise/sessions#new
#         author_session POST   /authors/sign_in(.:format)        devise/sessions#create
# destroy_author_session DELETE /authors/sign_out(.:format)       devise/sessions#destroy
#    new_author_password GET    /authors/password/new(.:format)   devise/passwords#new
#   edit_author_password GET    /authors/password/edit(.:format)  devise/passwords#edit
#        author_password PATCH  /authors/password(.:format)       devise/passwords#update
#                        PUT    /authors/password(.:format)       devise/passwords#update
#                        POST   /authors/password(.:format)       devise/passwords#create
#                   root GET    /                                 blog/posts#index
#          authors_posts GET    /authors/posts(.:format)          authors/posts#index
#                        POST   /authors/posts(.:format)          authors/posts#create
#       new_authors_post GET    /authors/posts/new(.:format)      authors/posts#new
#      edit_authors_post GET    /authors/posts/:id/edit(.:format) authors/posts#edit
#           authors_post GET    /authors/posts/:id(.:format)      authors/posts#show
#                        PATCH  /authors/posts/:id(.:format)      authors/posts#update
#                        PUT    /authors/posts/:id(.:format)      authors/posts#update
#                        DELETE /authors/posts/:id(.:format)      authors/posts#destroy
#                  about GET    /about(.:format)                  blog/pages#about
#                contact GET    /contact(.:format)                blog/pages#contact
#                  posts GET    /posts(.:format)                  blog/posts#index
#                   post GET    /posts/:id(.:format)              blog/posts#show
# 

Rails.application.routes.draw do

  	devise_for :authors
	root to: 'blog/posts#index'

	# /author/posts
	namespace :authors do 
		get '/acount' => 'accounts#edit', as: :account
		put '/info' => 'accounts#update_info', as: :info
		put '/change_password' => 'accounts#change_password', as: :change_password

		resources :posts do
			get 'publish' => 'posts#publish', on: :member, as: :publish
			get 'unpublish' => 'posts#unpublish', on: :member, as: :unpublish
		end
	end

	scope module: 'blog'  do
		get 'about' => 'pages#about', as: :about
		get 'contact' => 'pages#contact', as: :contact		
		get 'posts' => 'posts#index', as: :posts
		get 'posts/:id' => 'posts#show', as: :post
  	end
 	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <a class="navbar-brand" href="/">Flog<span class="light">blog</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="nav">
        <li class="nav-item active">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
  
        <% if author_signed_in? %>
          <li class="nav-item dropdown author-nav">
            <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag(current_author.gravatar_image_url) %>
              <%= current_author.display_name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <%= link_to 'My posts', authors_posts_path, class: "dropdown-item #{yield(:author)}" %>              
              <%= link_to 'Account', authors_account_path, class: "dropdown-item" %>              
              <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>              
            </div>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | FlogBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="container <%= controller_name%> <%= action_name %>">
      
        <% if flash.any? %>
          <% flash.keys.each do |key| %>
            <div class="alert alert-<%= key.to_s %> alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= flash[key] %>
            </div>
          <% end %>
        <% end %>

    	<%= yield %> 		
  	</div> 
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> | FlogBlog</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:300,400,700|Montserrat:400,400i,700" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="container <%= controller_name%> <%= action_name %>">
    	<%= yield %> 		
  	</div> 
  </body>
</html>